<!DOCTYPE html>
<html lang="en-us">
  <head>
  <title> Object Oriented Exception Handling in Perl </title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content=" The main goal of this article is to discuss in detail about exception handling in Perl and how to implement it using Error.pm. On our way, we&#39;ll be touching upon the advantages of using exception-handling over traditional error-handling mechanisms,..."/>
  <meta name="robots" content="index, follow">
  <meta name="google-site-verification" content="TZowffo_LX2mmsw2DbeNNbukCMnIOA8T-6CMJPiYllI" />

<meta property="twitter:card" content="summary">
<meta property="twitter:site" content="@PerlFoundation">
<meta property="og:url" content="http://localhost:1313/pub/2002/11/14/exception.html/" />
<meta property="og:title" content="Object Oriented Exception Handling in Perl" />
<meta property="og:description" content=" The main goal of this article is to discuss in detail about exception handling in Perl and how to implement it using Error.pm. On our way, we&#39;ll be touching upon the advantages of using exception-handling over traditional error-handling mechanisms,...">
<meta property="og:site_name" content="Perl.com" />

<meta property="og:type" content="article" />
<meta property="og:article:published_time" content="2002-11-11T11:11:11Z" />
<meta property="og:image" content="http://localhost:1313/images/_pub_2002_11_14_exception/111-error.gif" />


  <link rel="icon" href="/favicon.ico">
  <link href="/article/index.xml" rel="alternate" type="application/rss+xml" title="Perl.com - programming news, code and culture" />
  <link href="/article/index.xml" rel="feed" type="application/rss+xml" title="Perl.com - programming news, code and culture" />
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/css/perldotcom.css"/>


<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-50555-22', 'auto');
ga('create', 'UA-85734801-2', 'auto', 'editor');
ga('send', 'pageview');
ga('editor.send', 'pageview');
</script>

</head>
<body>

<div class="container-fluid full-wdith antonio">
 <div class="row">
  <div class="navbar-inverse" style="border-radius:none !important" role="navigation">
    <div class="container-fluid">
      <ul class="nav navbar-nav pull-right follow">
          <li>MORE:</li>
          <li><a href="https://perl.org">
              <img src="/images/site/perl-onion_20.png" alt="Perl Onion"></a><li>
          <li><a href="https://twitter.com/intent/follow?screen_name=perlfoundation">
              <img src="/images/site/twitter_20.png" alt="twitter"></a><li>
          <li><a href="/article/index.xml" />
              <img src="/images/site/rss_20.png" alt="rss"></a></li>
          <li><a href="https://github.com/tpf/perldotcom" />
              <img src="/images/site/github_light_20.png" alt="GitHub logo"></a></li>
      </ul>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-nav" href="/">
            <div class="header-logo">Perl.com</div>
          </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/about">
              <div class="circle">
                <img src="/images/site/perl-camel.png" alt="" />
              </div>
                  &nbsp;&nbsp;ABOUT</a>
          </li>
          <li><a href="/authors">
              <div class="circle">
                  <span class="glyphicon glyphicon-user txt-blue-major" aria-hidden="true"></span>
              </div>
                  &nbsp;&nbsp;AUTHORS</a>
          </li>
          <li><a href="/categories">
              <div class="circle">
                  <span class="glyphicon glyphicon-folder-open txt-blue-major" aria-hidden="true"></span>
              </div>
                  &nbsp;&nbsp;CATEGORIES</a>
          </li>
          <li><a href="/tags">
              <div class="circle">
                <span class="txt-blue-major" aria-hidden="true"><strong>#</strong></span>
              </div>
                  &nbsp;&nbsp;TAGS</a>
          </li>
          <li>
            <form class="search" name="ddg" action="https://duckduckgo.com/" method="get">
              <input type="text" name ="q" placeholder="SEARCH" />
              <input type="hidden" value="perl.com" name="sites" />
            </form>
          </li>
        </ul>
      </div>
    </div>
  </div>
 </div>
</div>


  <section id="content" role="main">
    <section class="entry-content">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <div class="row">
              <article class="fulltext">
              <h1 class="blog-post-title">Object Oriented Exception Handling in Perl</h1>
              <p class="blog-post-meta">Nov 14, 2002 by
              
              
                
                
                <a href="#author-bio-arun-udaya-shankar">Arun Udaya Shankar</a>
              
              </p>
              <img alt="" src=""/>
                

<p>The main goal of this article is to discuss in detail about exception handling in Perl and how to implement it using Error.pm. On our way, we&rsquo;ll be touching upon the advantages of using exception-handling over traditional error-handling mechanisms, exception handling with eval {}, problems with eval {} and the functionalities available in Fatal.pm. But by and large, our focus we&rsquo;ll be on using Error.pm for exception handling.</p>

<h3 id="what-is-an-exception">What Is an Exception ?</h3>

<p>An exception can be defined as an event that occurs during the execution of a program that deviates it from the normal execution path. Different types of errors can cause exceptions. They can range from serious errors such as running out of virtual memory to simple programming errors such as trying to read from an empty stack or opening an invalid file for reading.</p>

<p>An exception usually carries with it three important pieces of information:</p>

<ol>
<li>The type of exception - determined by the class of the exception object</li>
<li>Where the exception occurred - the stack trace</li>
<li>Context information - error message and other state information</li>
</ol>

<p>An exception handler is a piece of code used to gracefully deal with the exception. In the rest of article, the terms exception handler and catch block will be used interchangeably.</p>

<p>By choosing exceptions to manage errors, applications benefit a lot over traditional error-handling mechanisms. All the advantages of using exception handling are discussed in detail in the next section.</p>

<h3 id="advantages-of-using-exception-handling">Advantages of Using Exception Handling</h3>

<p>Object-oriented exception handling allows you to separate error-handling code from the normal code. As a result, the code is less complex, more readable and, at times, more efficient. The code is more efficient because the normal execution path doesn&rsquo;t have to check for errors. As a result, valuable CPU cycles are saved.</p>

<p>Another important advantage of OO exception handling is the ability to propagate errors up the call stack. This happens automatically without you, the programmer, explicitly checking for return values and returning them to the caller. Moreover, passing return values up the call stack is error prone, and with every hop there is a tendency to lose vital bits of information.</p>

<p>Most of the time, the point at which an error occurs is rarely the best place to handle it. So, the error needs to be propagated up the call stack. But by the time the error reaches the place where it can be handled suitably, a lot of the error context is lost. This is a common problem with traditional error-handling mechanisms (i.e. checking for return values and propagating them to the caller). Exceptions come to the rescue by allowing contextual information to be captured at the point where the error occurs and propagate it to a point where it can be effectively used/handled.</p>

<p>For instance, if you have a function <em>processFile()</em> that is the fourth method in a series of method calls made by your application. And also <em>func1()</em> is the only method interested in the errors that occur within <em>processFile()</em>. With a traditional error-handling mechanism, you would do the following to propagate the error code up the call stack until the error finally reaches <em>func1()</em>.</p>

<pre><code>  sub func3
  {
    my $retval = processFile($FILE);
    if (!$retval) { return $retval; }
    else {
      ....
    }
  }

  sub func2
  {
    my $retval = func3();
    if (!$retval) { return $retval; }
    else {
      ....
    }
  }

  sub func1 
  {
    my $retval = func2();
    if (!$retval) { return $retval; }
    else {
      ....
    }
  }

  sub processFile
  {
    my $file = shift;
    if (!open(FH, $file)) { return -1; }
    else {
      # Process the file
      return 1;
    }
  }
</code></pre>

<p>With OO exception handling, all you need to do is wrap the function call to <em>func2()</em> within the try block and handle the exceptions thrown from that block with an appropriate exception handler (catch block). The equivalent code with exception handling is shown below.</p>

<pre><code>   sub func1
   {
     try {
       func2();
     }
     catch IOException with {
       # Exception handling code here
     };  
   }

   sub func2 { func3(); ... }
   sub func3 { processFile($FILE); ... }

   sub processFile
   {
     my $file = shift;
     if (!open(FH, $file)) { 
       throw IOException(&quot;Error opening file &lt;$file&gt; - $!&quot;);
     }
     else {
       # Process the file
       return 1;
     }     
   }
</code></pre>

<p>Since <em>func1()</em> is the only function to possess a catch block, the exception that was thrown in the <em>processFile()</em> function is propagated all the way up to <em>func1()</em>, where it would be appropriately dealt with, by the catch block. The difference in the bloat factor and code obfuscation level between these two error handling techniques is obvious.</p>

<p>Finally, exceptions can be used to group related errors. By doing this, you will be able to handle related exceptions using a single exception handler. The inheritance hierarchy of the exception classes can be used to logically group exceptions. Thus, an exception handler can catch exceptions of the class specified by its parameter, or can catch exceptions of any of its subclass.</p>

<h3 id="let-s-do-it-in-perl">Let&rsquo;s Do It in Perl</h3>

<h3 id="perl-s-built-in-exception-handling-mechanism">Perl&rsquo;s Built-In Exception Handling Mechanism</h3>

<p>Perl has a built-in exception handling mechanism, a.k.a the eval {} block. It is implemented by wrapping the code that needs to be executed around an eval block and the $@ variable is checked to see if an exception occurred. The typical syntax is:</p>

<pre><code>  eval {
    ...
  };
  if ($@) {
    errorHandler($@);
  }
</code></pre>

<p>Within the eval block, if there is a syntax error or runtime error, or a die statement is executed, then an undefined value is returned by eval, and $@ is set to the error message. If there was no error, then $@ is guaranteed to be a null string.</p>

<p>What&rsquo;s wrong with this? Since the error message store in $@ is a simple scalar, checking the type of error that has occurred is error prone. Also, $@ doesn&rsquo;t tell us where the exception occurred. To overcome these issues, exception objects were incorporated in Perl 5.005.</p>

<p>From Perl 5.005 onward, you can do this:</p>

<pre><code>  eval {
    open(FILE, $file) || 
      die MyFileException-&gt;new(&quot;Unable to open file - $file&quot;);
  };

  if ($@) {
    # now $@ contains the exception object of type MyFileException
    print $@-&gt;getErrorMessage();  
    # where getErrorMessage() is a method in MyFileException class
  }
</code></pre>

<p>The exception class (MyFileException) can be built with as much functionality as desired. For example, you can get the calling context by using <em>caller()</em> in constructer of the exception class (typically <em>MyFileException::new()</em>).</p>

<p>It is also possible to test specific exception types as shown below:</p>

<pre><code>  eval {
    ....
  };

  if ($@) {
    if ($@-&gt;isa('MyFileException')) {  # Specific exception handler
      ....
    }
    else { # Generic exception handler
      ....
    }
  }
</code></pre>

<p>If the exception object implements stringification, by overloading the string operations, then the stringified version of the object would be available whenever $@ is used in string context. By constructing the overloading method appropriately, the value of $@ in string context can be tailored as desired.</p>

<pre><code>  package MyException;

  use overload ('&quot;&quot;' =&gt; 'stringify');
  ...
  ...
  sub stringify
  {
    my ($self) = @_;
    my $class = ref($self) || $self;

    return &quot;$class Exception: &quot; . $self-&gt;errMsg() . &quot; at &quot; . 
                                  $self-&gt;lineNo() . &quot; in &quot; . 
                                  $self-&gt;file();
    # Assuming that errMsg(), lineNo() &amp; file() are methods 
    # in the exception class
    # to store &amp; return error message, line number and source 
    # file respectively.
  }
</code></pre>

<p>When overloading the string operator &lsquo;&ldquo;&rsquo;, the overloading method (<em>stringify()</em> in our case) is expected to return a string representing the stringified form of the object. The stringify() method can return various context/state information about the exception object, as part of the string.</p>

<h3 id="problems-with-eval">Problems with eval</h3>

<p>The following are some of the issues in using the eval {} construct:</p>

<ul>
<li>Similar looking syntactic constructs can mean different things, based on the context.</li>
<li>eval blocks can be used for both, building dynamic code snippets as well as for exception handling</li>
<li>No builtin provision for cleanup handler a.k.a finally block</li>
<li>Stack trace if required, needs to maintained by writing custom code</li>
<li>Aesthetically unappealing (Although this is very subjective)</li>
</ul>

<h3 id="error-pm-to-the-rescue">Error.pm to the Rescue</h3>

<p>The Error.pm module implements OO exception handling. It mimics the try/catch/throw syntax available in other OO languages like Java and C++ (to name a few). It is also devoid of all the problems that are inherent when using eval. Since it&rsquo;s a pure perl module, it runs on almost all platforms where Perl runs.</p>

<h3 id="use-ing-error-pm">Use&rsquo;ing Error.pm</h3>

<p>The module provides two interfaces:</p>

<ol>
<li>Procedural interface for exception handling (exception handling constructs)</li>
<li>Base class for other exception classes</li>
</ol>

<p>The module exports various functions to perform exception handling. They will be exported if the :try tag is used in the use statement.</p>

<p>A typical invocation would look like this:</p>

<pre><code>  use Error qw(:try);

  try {
    some code;
    code that might thrown an exception;
    more code;
    return;
  }
  catch Error with {
    my $ex = shift;   # Get hold of the exception object
    handle the exception;
  }
  finally {
    cleanup code;
  };  # &lt;-- Remember the semicolon
</code></pre>

<p>Don&rsquo;t forget to include the trailing semicolon (;) after the closing brace. For those of you who want to know why: All these functions accept a code reference as their first parameter. For example, in the try block the code that follows try is passed in as a code reference (anonymous function) to the function <em>try(</em>).</p>

<h3 id="try-block">try Block</h3>

<p>An exception handler is constructed by enclosing the statements that are likely to throw an exception within a try block. If an exception occurs within the try block, then it is handled by the appropriate exception handler (catch block), associated with the try block. If no exceptions are thrown, then try will return the result of block.</p>

<p>The syntax is: try BLOCK EXCEPTION_HANDLERS</p>

<p>A try block should have at least one (or more) catch block(s) or one finally block.</p>

<h3 id="catch-block">Catch Block</h3>

<p>The try block associates the scope of its associated exception handlers. You associate exception handlers with a try block by providing one or more catch blocks directly after the try block:</p>

<pre><code>  try {
    ....
  }
  catch IOException with {
    ....
  }
  catch MathException with {
    ....
  };
</code></pre>

<p>The syntax is: catch CLASS with BLOCK</p>

<p>This enables all errors that satisfy the condition $ex-&gt;isa(CLASS) to be handled by evaluating BLOCK.</p>

<p>The BLOCK receives two parameters. The first is the exception being thrown and the second is a scalar reference. If this scalar reference is set on return from the catch block, then the try block continues as if there was no exception.</p>

<p>If the scalar referenced by the second parameter is not set, and no exceptions are thrown (within the catch block), then the current try block will return with the result from the catch block.</p>

<p>In order to propagate an exception, the catch block can choose to rethrow the exception by calling <em>$ex-&gt;throw()</em></p>

<h3 id="order-of-catch-blocks-matter">Order of Catch Blocks Matter</h3>

<p>The order of exception handlers is important. It&rsquo;s all the more critical if you have handlers at different levels in the inheritance hierarchy. Exception handlers that are built to handle exception types that are furthermost from the root of the hierarchy (Error) should be placed first in the list of catch blocks.</p>

<p>An exception handler designed to handle a specific type of object may be pre-empted by another handler whose exception type is a superclass of that type. This happens if the exception handler for that exception type appears earlier in the list of exception handlers.</p>

<p>For example:</p>

<pre><code>  try {
    my $result = $self-&gt;divide($value, 0);  
    # divide() throws DivideByZeroException
    return $result;  
  }
  catch MathException with {
    my $ex = shift;
    print &quot;Error: Caught MathException occurred\n&quot;;
    return;
  }
  catch DivideByZeroException with {
    my $ex = shift;
    print &quot;Error: Caught DivideByZeroException\n&quot;;
    return 0;
  };
</code></pre>

<p>Assuming the Inheritance hierarchy:</p>

<pre><code>  MathException is-a Error                 
       [ @MathException::ISA = qw(Error) ]
  DivideByZeroException is-a MathException 
       [ @DivideByZeroException::ISA = qw(MathException) ]
</code></pre>

<p>In the above code listing, the DivideByZeroException is caught by the first catch block instead of the second. That is because DivideByZeroException is a subclass of MathException. In other words, <em>$ex-&gt;isa(&lsquo;MathException&rsquo;)</em> returns true. Hence, the exception is handled by the code within the first catch block. Reversing the order of the catch blocks would ensure that the exception is caught by the correct exception handler.</p>

<h3 id="finally-block">Finally Block</h3>

<p>The final step in setting up an exception handler is providing a mechanism for cleaning up before control is passed to different part of the program. This can be achieved by enclosing the cleanup logic within the finally block. Code in the finally block is executed irrespective of what happens within the try block. Typical use of the finally block is to close files or in general to release any system resource.</p>

<p>If no exceptions are thrown, then none of the code in the catch block(s) gets executed. But the code in the finally block is always executed.</p>

<p>If an exception is thrown, then code in the appropriate catch block is executed. Once the execution of that code is complete, the finally block is executed.</p>

<pre><code>  try {
    my $file = join('.', '/tmp/tempfile', $$);

    my $fh = new FileHandle($file, 'w');
    throw IOException(&quot;Unable to open file - $!&quot;) if (!$fh);

    # some code that might throw an exception
    return;
  }
  catch Error with {
    my $ex = shift;
    # Exception handling code
  }
  finally {
    close($fh) if ($fh);    # Close the temporary file
    unlink($file);          # Delete the temporary file
  };
</code></pre>

<p>In the above code listing, a temporary file is created in the try block and the block also has some code that can potentially throw an exception. Irrespective of whether the try block succeeds, the temporary file has to be closed and deleted from the file system. This is accomplished by closing and deleting the file in the finally block.</p>

<p>Remember, only one finally block is allowed per try block.</p>

<h3 id="throw-statement">Throw Statement</h3>

<p>throw() creates a new &ldquo;Error&rdquo; object and throws an exception. This exception would be caught by a surrounding try block, if there is one. Otherwise the program will exit.</p>

<p>throw() can also be called on an existing exception to rethrow it. The code listing below illustrates how to rethrow an exception:</p>

<pre><code>  try {
    $self-&gt;openFile();
    $self-&gt;processFile();
    $self-&gt;closeFile();
  }
  catch IOException with {
    my $ex = shift;
    if (!$self-&gt;raiseException()) {
      warn(&quot;IOException occurred - &quot; . $ex-&gt;getMessage());
      return;
    }
    else { 
      $ex-&gt;throw(); # Re-throwing exception
    }
  };
</code></pre>

<h3 id="building-your-own-exception-class">Building Your Own Exception Class</h3>

<p>Setting the value of the $Error::Debug package variable to true, enables the capturing of stack trace for later retrieval using the stacktrace() method. (In case you are not familiar, stacktrace is a list of all the methods executed in sequence that lead to the exception).</p>

<p>The code snippet below creates the exception classes MathException, DivideByZero and OverFlowException. Where the latter two are subclasses of MathException and MathException by itself is derived from Error.pm</p>

<pre><code>  package MathException;

  use base qw(Error);
  use overload ('&quot;&quot;' =&gt; 'stringify');

  sub new
  {
    my $self = shift;
    my $text = &quot;&quot; . shift;
    my @args = ();

    local $Error::Depth = $Error::Depth + 1;
    local $Error::Debug = 1;  # Enables storing of stacktrace

    $self-&gt;SUPER::new(-text =&gt; $text, @args);
  }
  1;

  package DivideByZeroException;
  use base qw(MathException);
  1;

  package OverFlowException;
  use base qw(MathException);
  1;
</code></pre>

<h3 id="and-more">And More &hellip;</h3>

<p>The error modules has other special exception handling blocks, such as <em>except</em> and <em>otherwise</em>. They are deliberately not covered here because they are specific to Error.pm, and you won&rsquo;t find them in other OO languages. For those who are interested, please refer the POD documentation that is embedded within Error.pm.</p>

<h3 id="fatal-pm">Fatal.pm</h3>

<p>If you have some functions that return false on error and a true value on success, then you can use Fatal.pm to convert them into functions that throw exceptions on failure. It is possible to do this to both user defined functions as well as built-in functions (with some exceptions).</p>

<pre><code>  use Fatal qw(open close);

  eval { open(FH, &quot;invalidfile&quot;) }; 
  if ($@) {
    warn(&quot;Error opening file: $@\n&quot;);
  }

  ....
  ....

  eval { close(FH); }; 
  warn($@) if ($@);
</code></pre>

<p>By default, Fatal.pm catches every use of the fatalized functions i.e.</p>

<pre><code>  use Fatal qw(chdir);
  if (chdir(&quot;/tmp/tmp/&quot;)) {
    ....
  }
  else { 
    # Execution flow never reaches here
  }
</code></pre>

<p>If you are fortunate enough to have Perl 5.6 or later, then you can circumvent this by adding :void in the import list. All functions named after this in that import list will raise an exception only when they are called in void context i.e. when their return values are being ignored.</p>

<p>By changing the use statement, as shown below we can be sure that the code in the else block is executed when chdir() fails</p>

<pre><code>  use Fatal qw(:void chdir);
</code></pre>

<p>The code listing below illustrates the use of Fatal.pm in conjunction with Error.pm.</p>

<pre><code>  use Error qw(:try);
  use Fatal qw(:void open);

  try {
    open(FH, $file);
    ....
    openDBConnection($dsn);
    return;
  }
  catch DBConnectionException with {
    my $ex = shift;
    # Database connection failed
  }
  catch Error with {
    my $ex = shift;
    # If the open() fails, then we'll be here  
  };
</code></pre>

<h3 id="the-perl6-connection">The Perl6 Connection</h3>

<p>Since the exception handling syntax in Perl 6 is expected to be modeled closely against Error.pm as detailed in the Perl 6 RFC 63 Exception handling syntax - <a href="http://dev.perl.org/rfc/63.pod">http://dev.perl.org/rfc/63.pod</a>, also in RFC 80 and RFC 88. It would make sense for developers to make use of OO-ish exception handling capabilities in their code and later on migrate to the exception handling syntax in Perl 6, as and when it is available.</p>

<h3 id="conclusion">Conclusion</h3>

<p>The following are some of the key reasons to choose exception-handling mechanism over the traditional error-handling mechanisms:</p>

<ul>
<li>Error handling code can be separated from normal code</li>
<li>Less complex, more readable and more efficient code</li>
<li>Ability to propagating errors up the call stack</li>
<li>Ability to persist contextual information for the exception handler</li>
<li>Logical grouping of error types</li>
</ul>

<hr />

<p>So, stop returning error codes and start throwing exceptions.</p>

<p>Have an exceptional time !!</p>

              </article>
              <p><strong>Tags</strong></p>
              <div class="tags">
                <div class="category"><a href="/categories/development">development</a></div>
                
              </div>
            </div>
            
              
                
<div class="row" id="author-bio-arun-udaya-shankar">
  <div class="col-sm-2">
    
    <a href="/authors/arun-udaya-shankar/"><div class="circle-avatar" style="background-image:url(/images/site/avatar.png)"></div></a>
  </div>
  <div class="col-sm-10">
    <a href="/authors/arun-udaya-shankar/"><h3>Arun Udaya Shankar</h3></a>
    <p></p>
    <h5><a href="/authors/arun-udaya-shankar/">Browse their articles</a></h5>
  </div>
</div>

            
            <div class="row">
              <h3>Feedback</h3>
              <p>Something wrong with this article? Help us out by opening an issue or pull request on <a href="https://github.com/tpf/perldotcom/blob/master/content/legacy/_pub_2002_11_14_exception.md">GitHub</a></p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="latest-sidebar">

  <div class="row">
    <div class="col-sm-12 centering">
      <span style="font-size:1.8em" class="antonio txt-blue-major">OUR LATEST ARTICLES</span>
    </div>
  </div>
  
    
    
    <div class="row">
        <a href="http://localhost:1313/article/the-perl-admbassador-curtis-poe/">
      <div class="col-sm-3">
        <div class="circle-avatar" style="background-image:url(/images/the-perl-ambassador-curtis-poe/curtis-poe.jpg)"></div>
      </div>
      <div class="col-sm-9">
          <h6>The Perl Ambassador: Curtis &#39;Ovid&#39; Poe</h6>
          <p style="line-height:1"><small>The person behind the news of Perl</small></p>
      </div>
        </a>
    </div>
  
    
    
    <div class="row">
        <a href="http://localhost:1313/article/a-tour-with-net-ftp/">
      <div class="col-sm-3">
        <div class="circle-avatar" style="background-image:url(/images/a-tour-with-net-ftp/thumb_kidyes.jpg)"></div>
      </div>
      <div class="col-sm-9">
          <h6>A tour with Net::FTP</h6>
          <p style="line-height:1"><small>How to write an FTP client in Perl</small></p>
      </div>
        </a>
    </div>
  
    
    
    <div class="row">
        <a href="http://localhost:1313/article/shortcode_test/">
      <div class="col-sm-3">
        <div class="circle-avatar" style="background-image:url(/images/author/brian-d-foy.jpg)"></div>
      </div>
      <div class="col-sm-9">
          <h6>shortcode_test</h6>
          <p style="line-height:1"><small></small></p>
      </div>
        </a>
    </div>
  
    
    
    <div class="row">
        <a href="http://localhost:1313/article/listen-to-larry-wall-s-state-of-the-onion-2000-on-youtube/">
      <div class="col-sm-3">
        <div class="circle-avatar" style="background-image:url(/images/listen-to-larry-wall-s-state-of-the-onion-2000-on-youtube/thumb_larry-wall.jpg)"></div>
      </div>
      <div class="col-sm-9">
          <h6>Listen to Larry Wall&#39;s State of the Onion 2000 on YouTube</h6>
          <p style="line-height:1"><small></small></p>
      </div>
        </a>
    </div>
  
    
    
    <div class="row">
        <a href="http://localhost:1313/article/announcing-perl-7/">
      <div class="col-sm-3">
        <div class="circle-avatar" style="background-image:url(/images/announcing-perl-7/thumb_seven_on_blue_wall.jpg)"></div>
      </div>
      <div class="col-sm-9">
          <h6>Announcing Perl 7</h6>
          <p style="line-height:1"><small>Perl 5 with modern defaults</small></p>
      </div>
        </a>
    </div>
  
</div>
<div class="row" style="margin-top:20px">
  <div class="col-sm-12 centering">
  <script async src="/widget/toplinks/toplinks.js" type="text/javascript"></script>
    <div id="toplinks"></div>
  </div>
</div>

<div class="row" style="margin-top:20px">
  <div class="col-sm-12 centering">
    <a class="twitter-timeline" data-height="640" data-dnt="true" data-theme="dark" href="https://twitter.com/perlfoundation?ref_src=twsrc%5Etfw">Tweets by perlfoundation</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>

<div class="row" style="margin-top:20px">
  <div class="col-sm-12 centering">
    <script src="https://www.reddit.com/r/perl/hot/.embed?limit=10&t=all" type="text/javascript"></script>
  </div>
</div>



          </div>
        </div>
      </div>
    </section>
  </section>
<script>
 
var tables, i;
tables = document.getElementsByTagName('table');
for (i=0;i<tables.length;i++) {
  tables[i].className = 'table table-striped';
}
</script>
<div class="push"></div>
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-1">
        <h5>Site Map</h5>
        <ul>
        <li><a href="/">Home</a></li>
        <hr>
        <li><a href="/about">About</a></li>
        <hr>
        <li><a href="/authors">Authors</a></li>
        <hr>
        <li><a href="/categories">Categories</a></li>
        <hr>
        <li><a href="/tags">Tags</a></li>
        <hr>
        </ul>
      </div>
      <div class="col-md-3">
        <h5>Contact Us</h5>
        <p>To get in touch, send an email to: perl.com-editor@perl.org</p>
        <p><a href="https://perl.org">
              <img src="/images/site/perl-onion_20.png" alt="Perl Onion"></a>
          <a href="https://twitter.com/intent/follow?screen_name=perlfoundation">
              <img src="/images/site/twitter_20.png" alt="twitter"></a>
          <a href="/index.xml" /><img src="/images/site/rss_20.png" alt="rss"></a>
          <a href="https://github.com/tpf/perldotcom">
              <img src="/images/site/github_light_20.png" alt="GitHub logo"></a></p>
      </div>
      <div class="col-md-2">
          <h5>License</h5>
          <p>This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution-NonCommercial 3.0 Unported License</a>.</p>
          <p><a rel="license" href="https://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/3.0/88x31.png" /></a></p>
      </div>
      <div class="col-md-5">
          <h5>Legal</h5>
          <p>Perl.com and the authors make no representations with respect to the accuracy or completeness of the contents of all work on this website and specifically disclaim all warranties, including without limitation warranties of fitness for a particular purpose. The information published on this website may not be suitable for every situation. All work on this website is provided with the understanding that Perl.com and the authors are not engaged in rendering professional services. Neither Perl.com nor the authors shall be liable for damages arising herefrom.</p>
      </div>
    </div>
  </div>
</div>
<script src="/javascript/jquery.min.js"></script>
<script src="/javascript/bootstrap.min.js"></script>
<script data-no-instant>document.write('<script src="/livereload.js?port=1313&mindelay=10"></' + 'script>')</script></body>
</html>

